dashboard/urls.py
from django.urls import path
from . import views

app_name="dashboard"

urlpatterns = [
    path("", views.dashboard, name='dashboard')
]

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [
    path('create-job/', views.create_job, name='create-job'),
    path('update-job/<int:pk>/', views.update_job, name='update-job'),
    path('manage-jobs/', views.manage_jobs, name='manage-jobs'),
    path('apply-to-jobs/<int:pk>/', views.apply_to_job, name='apply-to-jobs'),
    path('all-applicants/<int:pk>/', views.all_applicants, name='all-applicants')
]

job_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls', namespace='website')),
    path('accounts/', include('user.urls', namespace='user')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('company/', include('company.urls', namespace='company')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('jobs/', include('job.urls', namespace='job')),
    path('admin/', admin.site.urls),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name='user'

urlpatterns = [
    path('register-applicant/', views.register_applicant, name='register-applicant'),
    path('register-recruiter/', views.register_recruiter, name='register-recruiter'),
    path('login/', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout')
]

job/models.py
from django.db import models
from user.models import User
from company.models import Company

# Create your models here.

class State(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Industry(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name = 'Industry'
        verbose_name_plural = 'Industries'
    
    def __str__(self):
        return self.name
    
class Job(models.Model):
    job_type_choices = (
        ('Remote', 'Remote'),
        ('Onsite', 'Onsite'),
        ('Hybrid', 'Hybrid'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    salary = models.PositiveIntegerField(default=35000)
    requirements = models.TextField()
    ideal_candidate = models.TextField()
    is_available = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    industry = models.ForeignKey(Industry, on_delete=models.DO_NOTHING, null=True, blank=True)
    state = models.ForeignKey(State, on_delete=models.DO_NOTHING, null=True, blank=True)
    job_type = models.CharField(max_length=20, choices=job_type_choices, null=True, blank=True)
    
    def __str__(self):
        return self.title
    
class ApplyJob(models.Model):
    status_choices = (
        ('Accepted', 'Accepted'),
        ('Declined', 'Declined'),
        ('Pending', 'Pending'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=status_choices)
    

job/forms.py
from django import forms
from .models import Job

class CreationJobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ('user', 'company')
        

class UpdateJobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ('user', 'company')

job/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from . models import Job, ApplyJob
from .forms import CreationJobForm, UpdateJobForm

# Create your views here.
def create_job(request):
    if request.user.is_recruiter and request.user.has_company:
        if request.method == 'POST':
            form = CreationJobForm(request.POST)
            if form.is_valid():
                var = form.save(commit=False)
                var.user = request.user
                var.company = request.user.company
                var.save()
                messages.info(request, 'New job has been created')
                return redirect('dashboard:dashboard')
            else:
                messages.warning(request, 'something when wrong')
                return redirect('create-job')
        else:
            form = CreationJobForm()
            context = {'form': form}
            return render(request, 'job/create_job.html', context)
    else:
        messages.warning(request, 'Permission Denied')
        return redirect('dashboard:dashboard')
    
def update_job(request, pk):
    job = Job.objects.get(pk=pk)
    if request.method == 'POST':
        form = UpdateJobForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            messages.info(request, 'You job info has been updated')
            return redirect('dashboard:dashboard')
        else:
            messages.warning(request, 'something when wrong')
    else:
        form = UpdateJobForm(instance=job)
        context = {'form': form}
        return render(request, 'job/update_job.html', context)
    
def manage_jobs(request):
    jobs = Job.objects.filter(user=request.user, company=request.user.company)
    context = {'jobs':jobs}
    return render(request, 'job/manage_jobs.html', context)


def apply_to_job(request, pk):
    if request.user.is_authenticated and request.is_applicant:
        job = Job.objects.get(pk=pk)
        if ApplyJob.objects.filter(user=request.user, job=pk).exists():
           messages.warning(request, 'Permission Denied')
           return redirect('dashboard:dashboard') 
        else:
            ApplyJob.objects.create(
                job=job,
                user = request.user,
                status = 'Pending'
            )
            messages.info(request, 'You have successfully applied! Please see dashboard')
            return redirect('dashboard:dashboard')
    else:
        messages.info(request, 'Please log in to continue')
        return redirect('user:login')
    
    
def all_applicants(request, pk):
    job = Job.objects.get(pk=pk)
    applicants = ApplyJob.objects.all()
    context = {'job':job, 'applicants':applicants}
    return render(request, 'job/all_applicants.html', context)
                

templates/job/all_applicants.html
{% extends 'job/base.html' %}
{% load static %}
{% block title %} All applied Jobs {% endblock %}
{% block content %}

    <section class="table ">

        <section class="table__inner">

            
            <section class="table__header">
            <h1>All Applicants for {{job.title}} Position</h1>
        </section>
        <section class="table__body">
            <table>
                <thead>
                    <tr>
                        <th>Frist Name</th>
                        <th>Surname</th>
                        <th>Location</th>
                        <th>Job Position/Title</th>
                        <th>Applicants Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                {% for applicant in applicants %}
                <tbody>
                    <tr>
                        <td>{{applicant.user.resume.first_name}}</td>
                        <td>{{applicant.user.resume.surname}}</td>
                        <td>{{applicant.user.resume.location}}</td>
                        <td>{{applicant.user.resume.job_title}}</td>
                        <td>{{applicant.timestamp}}</td>
                        <td><a href="#">Download resume</a></td>
                        <!-- We set the action as a button so it can be styled -->
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </section>
    </section>

    </section>

    {% endblock %}

templates/job/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC:wght@100;300;400;500;700;800;900&family=Open+Sans:wght@300;400;500;600;700;800&family=Poppins:wght@100;200;300;500;800;900&display=swap" rel="stylesheet">
    <link  rel="stylesheet"  href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'dashboard:dashboard' %}" class="navbar-logo"><img src="{% static 'images/logo.svg' %}" alt="logo"></a>
        <div class="navbar-menu">
            <a href="#jobs">Jobs</a>
            <a href="{% url 'job:create-job' %}">Create Jobs</a>
            <a href="{% url 'job:manage-jobs' %}">Manage Jobs</a>
            <a href="{% url 'user:logout' %}">Logout</a>
        </div>
        <div class="menu-toggle">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
    </nav>


    <!-- join -->
    {% block content %}

    {% endblock %}
    <!-- Footer -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="static/js/app.js"></script>
</body>
</html>

templates/job/create_job.html
{% extends 'job/base.html' %}
{% load static %}
{% block title %} Job Creation Page {% endblock %}
{% block content %}

    <section class="register">
        <h1>Create Job </h1>
        <form action="" method="POST">
            {% csrf_token %}
            <h1>Create A Resume</h1>
                <div class="form__input">
                    {{form}}
                </div>
                <button type="submit">Submit</button>
        </form>
    </section>

{% endblock %}

templates/job/manage_jobs.html
{% extends 'job/base.html' %}
{% load static %}
{% block title %} Manage Jobs Page {% endblock %}
{% block content %}


    <section class="table ">

        <section class="table__inner">

            
            <section class="table__header">
            <h1>Manage Jobs</h1>
        </section>
        <section class="table__body">
            <table>
                <thead>
                    <tr>
                        <th>Job title</th>
                        <th>Location</th>
                        <th>Salary (NGN)</th>
                        <th>No. of Applicants</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for job in jobs %}
                    <tr>
                        <td>{{job.title}}</td>
                        <td>{{job.location}}, {{job.compane.location}}</td>
                        <td>{{job.salary}}</td>
                        <td><a href="{% url 'job:all-applicants' job.pk %}">{{job.applyjob_set.count}} view all</a></td>
                        {% if job.is_available %}
                        <td><button>Active</button></td>
                        {% else %}
                        <td><button>Not active</button></td>
                        {% endif %}
                        <td><a href="#">Update job</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
    </section>

    </section>

  {% endblock %}