dashboard/urls.py
from django.urls import path
from . import views

app_name="dashboard"

urlpatterns = [
    path("", views.dashboard, name='dashboard')
]

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [
    path('create-job/', views.create_job, name='create-job'),
    path('update-job/<int:pk>/', views.update_job, name='update-job'),
    path('manage-jobs/', views.manage_jobs, name='manage-jobs'),
    path('apply-to-jobs/<int:pk>/', views.apply_to_job, name='apply-to-jobs'),
    path('all-applicants/<int:pk>/', views.all_applicants, name='all-applicants')
]

job_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls', namespace='website')),
    path('accounts/', include('user.urls', namespace='user')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('company/', include('company.urls', namespace='company')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('jobs/', include('job.urls', namespace='job')),
    path('admin/', admin.site.urls),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path
from . import views

app_name = 'resume'

urlpatterns = [
    path('update-resume/', views.update_resume, name='update-resume'),
    path('resume-details/', views.resume_details, name='resume-details'),
]

user/urls.py
from django.urls import path
from . import views

app_name='user'

urlpatterns = [
    path('register-applicant/', views.register_applicant, name='register-applicant'),
    path('register-recruiter/', views.register_recruiter, name='register-recruiter'),
    path('login/', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout')
]

website/urls.py
from django.urls import path
from . import views

app_name='website'

urlpatterns = [
    path('', views.home, name='home'),
    path('job-listing/', views.job_listing, name='job-listing'),
    path('job-details/<int:pk>/', views.job_details, name='job-details')
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render
from job.models import Job, ApplyJob
from .filter import Jobfilter

# Create your views here.
def home(request):
    filter = Jobfilter(request.GET, queryset=Job.objects.filter(is_available=True).order_by('-timestamp')[:6])
    context = {
        'filter':filter,
    }
    return render(request, 'website/home.html', context)


def job_listing(request):
    jobs = Job.objects.filter(is_available=True).order_by('-timestamp')
    context = {
        'jobs':jobs
        }
    return render(request, 'website/job_listing.html', context)


def job_details(request, pk):
    if ApplyJob.objects.filter(user=request.user, job=pk).exists():
        has_applied = True
    else:
        has_applied = False
    job = Job.objects.get(pk=pk)
    context = {
        'job':job,
        'has_applied':has_applied,
        }
    
    return render(request, 'website/job_detail.html', context)
    

templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC:wght@100;300;400;500;700;800;900&family=Open+Sans:wght@300;400;500;600;700;800&family=Poppins:wght@100;200;300;500;800;900&display=swap" rel="stylesheet">
    <link  rel="stylesheet"  href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
    {% block style %}
    {% endblock %}
    {% block content %}

    {% endblock %}

    <footer>
        <div class="footer-wrapper">
            <h3>Jobify</h3>
            <p>
                There are many variations of passages of Lorem Ipsum available, but the
                 majority have suffered alteration in some form, by injected 
            </p>
            <div class="social-media">
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-linkedin"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
        <div class="footer-wrapper">
            <h4>Explore</h4>
            <a href="#">Top Companies</a>
            <a href="#">Terms of Services</a>
            <a href="#">Podcast</a>
            <a href="#">Careers</a>
        </div>
        <div class="footer-wrapper">
            <h4>About</h4>
            <a href="#">FAQ</a>
            <a href="#">Get Inspired</a>
            <a href="#">Blog</a>
        </div>
        <div class="footer-wrapper">
            <h4>Support</h4>
            <a href="#">Customer Services</a>
            <a href="#">Trust & Safety</a>
            <a href="#">Partnership</a>
        </div>
        <div class="footer-wrapper">
            <h4>Community</h4>
            <a href="#">Community</a>
            <a href="#">Invite a Friend</a>
            <a href="#">Event</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/website/home.html
{% extends 'website/base.html' %}
{% load static %}
{% load humanize %}
{% block style %}
     <nav class="navbar">
        <a href="{% url 'website:home' %}" class="navbar-logo"><img src="{% static 'images/logo.svg' %}" alt="logo"></a>
        <div class="navbar-menu">
            <a href="{% url 'website:job-listing' %}">Check out Jobs </a>
            <a href="#companies">Companies</a>
            <a class="menu-button" href="{% url 'user:login' %}">Get started</a>
        </div>
        <div class="menu-toggle">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
    </nav>

{% endblock %}
{% block content %}

    <!-- header -->
    <header>
        
        <h1 class="header-title">
            WELCOME <br> <span>JOBIFY</span> <br> DASHBOARD
        </h1>
    </header>

    <!-- search -->
    <div class="search-wrapper">
        <div class="search-box">
            <div class="search-card">
                 {{filter.form.title}}
                <button type="submit" class="search-button">Search</button>
            </div>
        </div>
    </div>
    <!-- filter box -->
    <div class="filter-box">
        <div class="filter-dropdown">
            {{filter.form.state}}
            {{filter.form.job_type}}
            {{filter.form.industry}}     
        </div>
        <div class="filter-chosen">
            <div class="chosen-card">
                Remote <i class="fas fa-times-circle"></i>
            </div>
            <div class="chosen-card">
                Full time <i class="fas fa-times-circle"></i>
            </div>
            <div class="chosen-card">
                Financial Tech <i class="fas fa-times-circle"></i>
            </div>
            <div class="chosen-card">
                Entry Level <i class="fas fa-times-circle"></i>
            </div>
        </div>
        
   </div>

    <!-- job listing -->
    <section class="job-list" id="jobs">
        {% for job in filter.qs %}
        <div class="job-card">
            <div class="job-name">
                <img class="job-profile" src="{% static 'images/Tesla.png' %}" alt="">
                <div class="job-detail">
                    <h3>{{job.title}}</h3>
                    <span style="padding: 0.3rem .9rem;"> 
                        Industry: <small>{{ job.industry }}</small> 
                    </span>
                    <span style="padding: 0.3rem .9rem;"> 
                        Industry: <small> {{ job.job_type }}</small>
                    </span>
                    <span style="padding: 0.3rem .9rem;"> 
                        Industry:  <small>{{ job.location }}, {{ job.state }}</small>
                    </span>
                    <span style="padding: 0.3rem .9rem;"> 
                        Industry:  <small>{{ job.salary }}, {{ job.state }}</small>
                    </span>
                </div>
            </div>
            <div class="job-label"> 
                <a class="label-a" href="#">HTML</a>
                <a class="label-b" href="#">CSS</a>
                <a class="label-c" href="#">Javascripts</a>
            </div>
            <div class="job-posted">
                <small>{{job.timestamp|naturaltime}}</small>
            </div>
        </div>
        {% endfor %}
        <button class="job-more">More List</button>
    </section>

    <!-- join -->

    <section class="join">
        <div class="join-detail">
            <h1 class="section-title">LETS START YOUR NEW JOB WITH US</h1>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
            </p>
            <button class="join-button">Join Now</button>
        </div>
    </section>

    <!-- featured company -->
    <section class="featured" id="companies">
        <h1 class="section-title">Featured Companies</h1>
        <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
        </p>
        <div class="featured-wrapper">
            <div class="featured-card">
                <img src="{% static 'images/ebay.jpg' %}" class="featured-image" alt="">
                <p>Ebay</p>
                <button class="featured-button">View 2 Jobs</button>
            </div>
            <div class="featured-card">
                <img src="{% static 'images/youtube.jpg' %}" class="featured-image" alt="">
                <p>Youtube</p>
                <button class="featured-button">View 1 Jobs</button>
            </div>
            <div class="featured-card">
                <img src="{% static 'images/tiktok.jpg' %}" class="featured-image" alt="">
                <p>Tiktok</p>
                <button class="featured-button">View 3 Jobs</button>
            </div>
            <div class="featured-card">
                <img src="{% static 'images/Tesla.png' %}" class="featured-image" alt="">
                <p>Tesla</p>
                <button class="featured-button">View 3 Jobs</button>
            </div>
            <div class="featured-card">
                <img src="{% static 'images/chrome.jpg' %}" class="featured-image" alt="">
                <p>Chrome</p>
                <button class="featured-button">View 5 Jobs</button>
            </div>
            <div class="featured-card">
                <img src="{% static 'images/react.jpg' %}" class="featured-image" alt="">
                <p>React</p>
                <button class="featured-button">View 4 Jobs</button>
            </div>
        </div>
    </section>

   
    <!-- Footer -->

{% endblock %}
            <!-- <a href="#companies">Companies</a>
            <a href="#testimony">Testimonial</a>
            <a class="menu-button" href="{% url 'user:login' %}">Get started</a> -->

templates/website/job_detail.html
{% extends 'website/base.html' %}
{% load static %}
{% load humanize %}

{% block style %}
 <nav class="navbar" style="background: #a1defa;">
    {% if request.user.is_athenticated %}
    <a href="{% url 'dashboard:dashboard' %}" class="navbar-logo"><img src="{% static 'images/logo.svg' %}" alt="logo"></a>
    {% else %}
    <a href="{% url 'website:home' %}" class="navbar-logo"><img src="{% static 'images/logo.svg' %}" alt="logo"></a>
        {% endif %}
        <div class="navbar-menu">
            {% if request.user.is_authenticated %}
            <a href="#">Apply for Jobs</a>
            <a href="{% url 'resume:update-resume' %}">Create resume</a>
             <a href="{% url 'website:job-listing' %}">Find Jobs </a>
            {% else %}
            <a href="#">Apply for Jobs</a>
            <a href="#companies">Companies</a>
            <a class="menu-button" href="{% url 'user:login' %}">Get started</a>
            {% endif %}
        </div>
        <div class="menu-toggle">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
    </nav>

{% endblock %}
{% block content %}

    <!-- header -->
    <section class="job-details">
        <h1>Customer Support Executor</h1>
        <p style="color: #fff;">{{job.location}} | Remote | NGN{{job.salary|intcomma}}</p>
        {% if request.user.is_authenticated %}
        {% if has_applied == True %}
        <p style="color: #fff;">You have already applied for this Job</p>
        {% else %}
        <a href="{% url 'job:apply-to-jobs' job.pk %}" class="btns">Apply for Job</a>
        {% endif%}
        {% else %}
        <a href="{% url 'user:login' %}" class="btns">Login to Apply</a>
        {% endif %}
    </section>
     
    <section id="jobs" class="company-info">
        <div>
            <div class="flex-center-row">
                <h2>Job Requirement</h2>
                <p>
                   {{job.requirements}}
                </p>
            </div>
            <div>
                <h2>Ideal Condidate</h2>
                <p>
                    {{job.ideal_candidate}}
                </p>
            </div>
        </div>
        <div class="job-others">
            <div>
                <h2>About the Company</h2>
                <p>Company name: {{job.company.name}}</p>
                <p>Company Location: {{job.company.city}}, {{job.company.state}}</p>
                <p>Company establish Year: {{job.company.est_date}}</p>
                <div class="inner">
                    <span>Last updated 3mins ago</span>
                </div>
            </div>
            <div>
                <h2>Other Details</h2>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                <div class="inner">
                    <span>Last updated 3mins ago</span>
                </div>
            </div>
            <div>
                <h2>Related jobs</h2>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                <div class="inner">
                    <span>Last updated 3mins ago</span>
                </div>
            </div>
        </div>
    </section>
  {% endblock %}

templates/website/job_listing.html
{% extends 'website/base.html' %}
{% load static %}
{% load humanize %}

{% block style %}
 <nav class="navbar" style="background: #a1defa;">
        <a href="{% url 'website:home' %}" class="navbar-logo"><img src="{% static 'images/logo.svg' %}" alt="logo"></a>
        <div class="navbar-menu">
            <a href="#">Apply for Jobs</a>
            <a href="#companies">Companies</a>
            <a class="menu-button" href="{% url 'user:login' %}">Get started</a>
        </div>
        <div class="menu-toggle">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
    </nav>

{% endblock %}
{% block content %}

<section class="job_listings" >
        <h1 class="section-title">Featured Companies</h1>
        
        <div class="featured-wrapper" style="text-align: left;">
            {% if jobs %}
            {% for job in jobs %}
            <div class="featured-card">
                <h3>{{job.title}}</h3>
                <p class="card-text">
                  Job Location: {{job.location}}
                </p>
                <p class="card-text">Job Salary: {{job.salary|intcomma}}</p>
                <a href="{% url 'website:job-details' job.pk %}">View details</a>
                <div class="card-footer">
                    <small class="text-muted">Created {{ job.timestamp|naturaltime }}</small>
                </div>
            </div>
           {% endfor %}
           {% endif %}
        </div>
    </section>

{% endblock %}