company/urls.py
from django.urls import path
from . import views

app_name='company'

urlpatterns = [
    path('update-company/', views.update_company, name='update-company'),
    path('company-details/<int:pk>/', views.company_details, name='company-details')
]

dashboard/urls.py
from django.urls import path
from . import views

app_name="dashboard"

urlpatterns = [
    path("", views.dashboard, name='dashboard')
]

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [
    path('create-job/', views.create_job, name='create-job'),
    path('update-job/<int:pk>/', views.update_job, name='update-job'),
    path('manage-jobs/', views.manage_jobs, name='manage-jobs'),
    path('apply-to-jobs/<int:pk>/', views.apply_to_job, name='apply-to-jobs'),
    path('all-applicants/<int:pk>/', views.all_applicants, name='all-applicants')
]

job_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls', namespace='website')),
    path('accounts/', include('user.urls', namespace='user')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('company/', include('company.urls', namespace='company')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('jobs/', include('job.urls', namespace='job')),
    path('admin/', admin.site.urls),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path
from . import views

app_name = 'resume'

urlpatterns = [
    path('update-resume/', views.update_resume, name='update-resume'),
    path('resume-details/', views.resume_details, name='resume-details'),
]

user/urls.py
from django.urls import path
from . import views

app_name='user'

urlpatterns = [
    path('register-applicant/', views.register_applicant, name='register-applicant'),
    path('register-recruiter/', views.register_recruiter, name='register-recruiter'),
    path('login/', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout')
]

website/urls.py
from django.urls import path
from . import views

app_name='website'

urlpatterns = [
    path('', views.home, name='home'),
    path('job-listing/', views.job_listing, name='job-listing'),
    path('job-details/<int:pk>/', views.job_details, name='job-details')
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

# Create your views here.

def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC:wght@100;300;400;500;700;800;900&family=Open+Sans:wght@300;400;500;600;700;800&family=Poppins:wght@100;200;300;500;800;900&display=swap" rel="stylesheet">
    <link  rel="stylesheet"  href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar">
        <a href="#" class="navbar-logo"><img src="{% static 'images/logo.svg' %}" alt="logo"></a>
        <div class="navbar-menu">
            {% if request.user.is_authenticated %}
            {% if request.user.is_applicant%}
            {% if request.user.has_resume %}
            <a href="#">Apply for Jobs</a>
            {% else %}
            <a href="{% url 'resume:update-resume' %}">Create resume</a>
            {% endif %}
            <a href="#companies">Companies</a>
             <a href="{% url 'website:job-listing' %}">Find Jobs </a>
            {% elif request.user.is_recruiter %}
            {% if request.user.has_company %}
            <a href="{% url 'job:create-job' %}">Create Jobs</a>
            <a href="{% url 'job:manage-jobs' %}">Manage Jobs</a>
            {% else %}
            <a href="{% url 'company:update-company' %}">Create company</a>
            {% endif %}
            <a href="#companies">Companies</a>
            {% endif %}
            <a href="{% url 'user:logout' %}">Logout</a>
            {% endif %}
        </div>
        <div class="menu-toggle">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

    <footer>
        <div class="footer-wrapper">
            <h3>Jobify</h3>
            <p>
                There are many variations of passages of Lorem Ipsum available, but the
                 majority have suffered alteration in some form, by injected 
            </p>
            <div class="social-media">
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-linkedin"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
        <div class="footer-wrapper">
            <h4>Explore</h4>
            <a href="#">Top Companies</a>
            <a href="#">Terms of Services</a>
            <a href="#">Podcast</a>
            <a href="#">Careers</a>
        </div>
        <div class="footer-wrapper">
            <h4>About</h4>
            <a href="#">FAQ</a>
            <a href="#">Get Inspired</a>
            <a href="#">Blog</a>
        </div>
        <div class="footer-wrapper">
            <h4>Support</h4>
            <a href="#">Customer Services</a>
            <a href="#">Trust & Safety</a>
            <a href="#">Partnership</a>
        </div>
        <div class="footer-wrapper">
            <h4>Community</h4>
            <a href="#">Community</a>
            <a href="#">Invite a Friend</a>
            <a href="#">Event</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>